# Change these first
owner: seyitacar # Your GitHub organization or username, where this repository lives
repo: evcilimstatus # The name of this repository

sites:
  - name: Anasayfa
    url: https://evcil.im/
  - name: Evcil Profil Sayfaları
    url: https://ben.evcil.im/varsayilan/
  - name: Evcil Profil Düzenleme
    url: https://ben.evcil.im/login
  - name: E-posta Servisleri
    url: witcher.mxrouting.net
    port: 465
    check: "tcp-ping"

status-website:
  # Add your custom domain name, or remove the `cname` line if you don't have a domain
  # Uncomment the `baseUrl` line if you don't have a custom domain and add your repo name there
  cname: durum.evcil.im
  # baseUrl: /your-repo-name
  logoUrl: https://evcil.im/wp-content/uploads/2025/03/ben-evcilim.svg
  name: Sistem Durumu - Ben Evcilim
  introTitle: "Ben Evcilim Hizmet Durumu"
  introMessage: Bu sayfa Ben Evcilim hizmetlerinin anlık sistem durumları ve çevrimiçi kalma grafiğini gösterir. [Anasayfa (evcil.im)](https://evcil.im/), [Evcil Profil Sayfaları (ben.evcil.im/varsayilan)](https://ben.evcil.im/varsayilan/), [Evcil Profil Düzenleme (ben.evcil.im/login)](https://ben.evcil.im/login) ve E-posta Servislerini düzenli olarak kontrol eder.
  navbar:
    - title:
      href: /
  theme: light
  favicon: https://example.com/favicon.png
  faviconSvg: https://evcil.im/wp-content/uploads/2025/03/ben-evcilim-favicon.svg
  metaTags:
    - name: "robots"
      content: "noindex"
  robotsText: "User-agent: * \n Disallow: /"
  i18n:
      activeIncidents: Kesintiler
      allSystemsOperational: Tüm sistemler çevrimiçi
      incidentReport: "#$NUMBER Numaralı Kesinti Raporu →"
      activeIncidentSummary: $DATE tarihinde $POSTS gönderisiyle açıldı
      incidentTitle: Kesinti $NUMBER Detayları
      incidentDetails: Kesinti Detayları
      incidentFixed: Düzeltildi
      incidentOngoing: Üzerinde Çalışılıyor
      incidentOpenedAt: Başlangıç Tarihi:
      incidentClosedAt: Bitiş Tarihi:
      incidentViewOnGitHub: GitHubda görüntüleyin ve abone olun
      incidentCommentSummary: $DATE tarihinde $AUTHOR tarafından yayınlandı.
      incidentBack: ← Tüm kesintilere geri dön
      pastIncidents: Geçmiş Kesintiler
      pastIncidentsResolved: $MINUTES dakika içinde $POSTS gönderi ile çözüldü
      liveStatus: Anlık Durum
      overallUptime: "Toplam Çevrimiçi Süre: $UPTIME"
      overallUptimeTitle: Toplam Çevrimiçi Süre
      averageResponseTime: "Ortalama Yanıt Süresi: $TIMEms"
      averageResponseTimeTitle: Ortalama yanıt süresi
      sevelDayResponseTime: 7 günlük yanıt süresi
      responseTimeMs: Yanıt süresi (ms)
      up: Çalışıyor
      down: Kesinti
      degraded: Bozulmuş
      ms: ms
      loading: Yükleniyor
      navGitHub: GitHub
      footer: Bu sayfa [Ben Evcilim](https://evcil.im) projesinin sistem durumlarını takip için tasarlanmıştır.
      rateLimitExceededTitle: Rate limit exceeded
      rateLimitExceededIntro: You have exceeded the number of requests you can do in an hour, so you'll have to wait before accessing this website again. Alternately, you can add a GitHub Personal Access Token to continue to use this website.
      rateLimitExceededWhatDoesErrorMean: What does this error mean?
      rateLimitExceededErrorMeaning: This website uses the GitHub API to access real-time data about our websites' status. By default, GitHub allows each IP address 60 requests per hour, which you have consumed.
      rateLimitExceededErrorHowCanFix: How can I fix it?
      rateLimitExceededErrorFix: You can wait for another hour and your IP address' limit will be restored. Alternately, you can add your GitHub Personal Access Token, which gives you an additional 5,000 requests per hour.
      rateLimitExceededGeneratePAT: Learn how to generate a Personal Access Token
      rateLimitExceededHasSet: You have a personal access token set.
      rateLimitExceededRemoveToken: Remove token
      rateLimitExceededGitHubPAT: GitHub Personal Access Token
      rateLimitExceededCopyPastePAT: Copy and paste your token
      rateLimitExceededSaveToken: Save token
      errorTitle: An error occurred
      errorIntro: An error occurred in trying to get the latest status details.
      errorText: You can try again in a few moments.
      errorHome: Go to the homepage
      pastScheduledMaintenance: Past Scheduled Maintenance
      scheduledMaintenance: Scheduled Maintenance
      scheduledMaintenanceSummaryStarted: Started at $DATE for $DURATION minutes
      scheduledMaintenanceSummaryStarts: Starts at $DATE for $DURATION minutes
      startedAt: Başlangıç
      startsAt: Başlama Zamanı
      duration: Süre
      durationMin: $DURATION dakika
      incidentCompleted: Tamamlandı
      incidentScheduled: Planlandı
      duration24H: 24s
      duration7D: 7g
      duration30D: 30g
      duration1Y: 1y
      durationAll: tümü
      locale: tr-TR

# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
