# Change these first
owner: seyitacar # Your GitHub organization or username, where this repository lives
repo: evcilimstatus # The name of this repository

sites:
  - name: Anasayfa
    url: https://evcil.im/
  - name: Evcil Profil Sayfaları
    url: https://ben.evcil.im/varsayilan/
  - name: Evcil Profil Düzenleme
    url: https://ben.evcil.im/login
  - name: E-posta Servisleri
    url: witcher.mxrouting.net
    port: 465
    check: "tcp-ping"

status-website:
  # Add your custom domain name, or remove the `cname` line if you don't have a domain
  # Uncomment the `baseUrl` line if you don't have a custom domain and add your repo name there
  cname: durum.evcil.im
  # baseUrl: /your-repo-name
  logoUrl: https://evcil.im/wp-content/uploads/2025/03/ben-evcilim.svg
  name: Sistem Durumu - Ben Evcilim
  introTitle: "Ben Evcilim Hizmet Durumu"
  introMessage: Bu sayfa Ben Evcilim hizmetlerinin anlık sistem durumları ve çevrimiçi kalma grafiğini gösterir. [Anasayfa (evcil.im)](https://evcil.im/), [Evcil Profil Sayfaları (ben.evcil.im/varsayilan)](https://ben.evcil.im/varsayilan/), [Evcil Profil Düzenleme (ben.evcil.im/login)](https://ben.evcil.im/login) ve E-posta Servislerini düzenli olarak kontrol eder.
  navbar:
    - title:
      href: /
  theme: light

# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
